AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Boilerplate project for creating a basic lambda function

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Timeout: 120
      Role: arn:aws:iam::096174575712:role/lambda_vpc
      Environment:
        Variables:
          PROGRAM_NAME: BoilerplateFunction
          NODE_ENV: dev
          SUPPRESS_NO_CONFIG_WARNING: 1
